# Generated by Django 3.2.3 on 2023-03-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productitem_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='IPFS_hash',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='img_url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_image',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
