# Generated by Django 3.2.16 on 2023-03-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230312_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcartitem',
            name='added_on',
            field=models.DateTimeField(null=True),
        ),
    ]
