# Generated by Django 3.2.3 on 2023-03-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230321_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoporder',
            name='transaction_hash',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
