# Generated by Django 3.2.3 on 2023-03-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shoporder_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoporder',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
