# Generated by Django 3.2.3 on 2023-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='prize',
            field=models.FloatField(),
        ),
    ]
